services:
  postgres:
    image: postgres:17
    container_name: bankatm-postgres
    restart: always
    environment:
      POSTGRES_DB: bankatm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: bankatm-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: